# Explore here

In [9]:
#Librerias

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

## Paso 1: Carga del conjunto de datos

In [2]:
df = pd.read_csv('https://breathecode.herokuapp.com/asset/internal-link?id=927&path=AB_NYC_2019.csv')

df.head()

,id,name,host_id,host_name,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,last_review,reviews_per_month,calculated_host_listings_count,availability_365
0,2539,Clean & quiet apt home by the park,2787,John,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,2018-10-19,0.21,6,365
1,2595,Skylit Midtown Castle,2845,Jennifer,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2019-05-21,0.38,2,355
2,3647,THE VILLAGE OF HARLEM....NEW YORK !,4632,Elisabeth,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,NaN,NaN,1,365
3,3831,Cozy Entire Floor of Brownstone,4869,LisaRoxanne,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,2019-07-05,4.64,1,194
4,5022,Entire Apt: Spacious Studio/Loft by central park,7192,Laura,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,2018-11-19,0.10,1,0

In [3]:
df.to_csv('../data/raw/datos_airbnb_nyc.csv', index=False)

## Paso 2: Realiza un EDA completo

### Paso 1 EDA:
### Planteamiento del problema y recopilación de datos

Problema: Predicción de precios en NYC para Airbnb

### Paso 2 EDA:

### Exploración y limpieza de datos

In [4]:
#Obtener información de tipos de datos y valores nulos de cada columna
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 16 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   id                              48895 non-null  int64
 1   name                            48879 non-null  str
 2   host_id                         48895 non-null  int64
 3   host_name                       48874 non-null  str
 4   neighbourhood_group             48895 non-null  str
 5   neighbourhood                   48895 non-null  str
 6   latitude                        48895 non-null  float64
 7   longitude                       48895 non-null  float64
 8   room_type                       48895 non-null  str
 9   price                           48895 non-null  int64
 10  minimum_nights                  48895 non-null  int64
 11  number_of_reviews               48895 non-null  int64
 12  last_review                     38843 non-null  str
 13  reviews_per_month               38843 non-null  float64
 14  calculated_host_listings_count  48895 non-null  int64
 15  availability_365                48895 non-null  int64
dtypes: float64(3), int64(7), str(6)
memory usage: 6.0 MB

- Tenemos 48.895 filas y 16 columnas.

- También podemos observar que tenemos muchos valores nulos en las columnas name, host_name, last_review y reviews_per_month.

- En los tipos de datos podemos inferir que tenemos 10 variables numéricas y 6 categóricas.

Ahora procedemos a analizar si tenemos duplicados y en caso de que hubiera, eliminarlos.

In [5]:
#Analizar si hay duplicados restando una columna específica (id)
print(df.drop(columns=['id']).duplicated().sum())

#Analizar si en una columna específica hay duplicados (id)
print(df['id'].duplicated().sum())

#Analizar cantidad total de duplicados, todas las columnas
print(df.duplicated().sum())

0
0
0

Luego de este breve análisis, podemos concluir que no hay duplicados.

A continuación, vamos a eliminar la información irrelevante.

In [6]:
df.columns

Index(['id', 'name', 'host_id', 'host_name', 'neighbourhood_group',
       'neighbourhood', 'latitude', 'longitude', 'room_type', 'price',
       'minimum_nights', 'number_of_reviews', 'last_review',
       'reviews_per_month', 'calculated_host_listings_count',
       'availability_365'],
      dtype='str')

In [7]:
df.drop(['id', 'name', 'host_id', 'host_name', 'last_review', 'reviews_per_month'],axis=1,inplace=True)

df.head()

,neighbourhood_group,neighbourhood,latitude,longitude,room_type,price,minimum_nights,number_of_reviews,calculated_host_listings_count,availability_365
0,Brooklyn,Kensington,40.64749,-73.97237,Private room,149,1,9,6,365
1,Manhattan,Midtown,40.75362,-73.98377,Entire home/apt,225,1,45,2,355
2,Manhattan,Harlem,40.80902,-73.94190,Private room,150,3,0,1,365
3,Brooklyn,Clinton Hill,40.68514,-73.95976,Entire home/apt,89,1,270,1,194
4,Manhattan,East Harlem,40.79851,-73.94399,Entire home/apt,80,10,9,1,0

Argumentos

- Las columnas id y host_id no son relevantes para el precio, dado que son identificadores.
- Las columnas name y host_name no son relevantes para el precio, ya que no nos ayuda a definir la propiedad.
- La columna last_review no es relevante para el precio porque es un dato anecdótico.
- La columna reviews_per_month tiene casi la misma información que number_of_reviews, solo que dividido por 12.

### Paso 3 EDA:

### Análisis de variables univariante

- ***Analisis de variables categóricas***

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 48895 entries, 0 to 48894
Data columns (total 10 columns):
 #   Column                          Non-Null Count  Dtype
---  ------                          --------------  -----
 0   neighbourhood_group             48895 non-null  str
 1   neighbourhood                   48895 non-null  str
 2   latitude                        48895 non-null  float64
 3   longitude                       48895 non-null  float64
 4   room_type                       48895 non-null  str
 5   price                           48895 non-null  int64
 6   minimum_nights                  48895 non-null  int64
 7   number_of_reviews               48895 non-null  int64
 8   calculated_host_listings_count  48895 non-null  int64
 9   availability_365                48895 non-null  int64
dtypes: float64(2), int64(5), str(3)
memory usage: 3.7 MB